server:
  port: 2011

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@

  ai:
    dashscope:
      # 需要替换为你自己的 key
      api-key: your-api-key
      chat:
        options:
          model: qwen-plus

# searchAPI
search-api:
  # 需要替换为你自己的 key
  api-key: 你的 API Key

# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG
